---
name: Win32-Security-EFS
version: 0.07
author:
  - 'Sascha Kiefer, L<esskar@cpan.org>'
abstract: |-
  Perl interface to functions that assist in working
  with EFS (Encrypted File System) under Windows plattforms.
license: perl
requires:
  File::Spec: 3.05
  Win32: 0.24
  Win32::API: 0.41
provides:
  Win32::Security::EFS:
    file: lib/Win32/Security/EFS.pm
    version: 0.07
generated_by: Module::Build version 0.2611
